version: '3'

services:
  db:
    container_name: postgresql
    image: postgres
    volumes:
      - ./db/db_data:/var/lib/postgresql/data
    ports:
      - ${POSTGRES_PORT}:5432   
    restart: always
    healthcheck:
      test: pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}
      interval: 10s
      timeout: 3s
      retries: 5
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}

  migrations:
    image: migrate/migrate
    container_name: migrations
    command: ["-path", "/migrations", "-database", "postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:${POSTGRES_PORT}/${POSTGRES_DB}?sslmode=disable", "up"]
    volumes:
      - ./db/migrations:/migrations
    restart: on-failure
    depends_on:
      db:
        condition: service_healthy

  app:
    container_name: app
    build: ./
    # command: /bin/sh -c  "sleep infinity & wait"
    volumes:
      - ./images:/images
    ports:
      - 80:80
    restart: always
    depends_on:
      - migrations
    environment:
      POSTGRES_HOST: db
